layout_spectrum: 0.7634408
color:
  saturation: 0.5824373
  brandStrength: 0.4964158
  lightness: 0.4336918
  brandColors:
    - '#F2EBDF'
    - '#282727'
    - '#B47E6E'
    - '#C6BDB4'
    - '#6D5D42'
  rhythmicContrast: 0.5806451
typography_spectrum: 0.4731183
name: Limbus
