collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8763441
  lightness: 0.8154122
  brandStrength: 0.8189964
  brandColors:
    - '#1E0D0C'
    - '#FFFFFB'
    - '#FFA253'
    - '#42CE5D'
    - '#03FFF3'
  rhythmicContrast: 0.7204301
typography_spectrum: 0.4731183
layout_spectrum: 0.9802867
name: Limbus
